# Generated by Django 5.2.8 on 2025-12-06 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0001_initial"),
        ("cursos", "0001_initial"),
        ("matriculas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="valor_pago",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matriculas",
                to="alunos.aluno",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matriculas",
                to="cursos.curso",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativa", "Ativa"),
                    ("cancelada", "Cancelada"),
                    ("concluida", "Concluída"),
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                ],
                default="ativa",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matricula",
            unique_together={("aluno", "curso")},
        ),
    ]
